imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        console:
            type:   console
            bubble: false
            channels: [!doctrine]
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event, !doctrine]
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'btkkzztb@gmail.com'
            to_email:   'btkkzztb@gmail.com'
            subject:    'Promo Code Found!'
            level:      emergency